# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         BDB-Wrapper
version:      0.31
version_from: lib/BDB/Wrapper.pm
installdirs:  site
requires:
    BerkeleyDB:                    0
    File::Spec:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
