---
abstract: 'The module to use BerkeleyDB.pm with good option easily'
author:
  - 'Hajime Kurita / Admin of http://sakuhindb.com/ & http://minakoe.jp/'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: BDB-Wrapper
no_index:
  directory:
    - t
    - inc
requires:
  BerkeleyDB: 0
  File::Spec: 0
version: 0.47
